---

- name: Install Nginx
  apt: pkg=nginx state=installed update_cache=true
  register: nginxinstalled
  notify:
    - Start Nginx

- name: Disable Default Site
  when: nginxinstalled|success
  file: dest=/etc/nginx/sites-enabled/default state=absent

- name: Add tempstats site
  when: nginxinstalled|success
  register: tempstatsconfig
  template: src=tempstats.j2 dest=/etc/nginx/sites-available/{{ '{{' }} domain {{ '}}'  }}.conf owner=root group=root

- name: Enable tempstats config
  when: tempstatsconfig|success
  file: src=/etc/nginx/sites-available/{{ '{{' }} domain {{ '}}'  }}.conf dest=/etc/nginx/sites-enabled/{{ '{{' }} domain {{ '}}'  }}.conf state=link


- name: Create Web root
  when: nginxinstalled|success
  file: dest=/var/www/{{ '{{' }} name {{ '}}'  }} mode=775 state=directory owner=www-data group=www-data
  notify:
    - Reload Nginx

- name: Web Root Permissions
  when: nginxinstalled|success
  file: dest=/var/www/{{ '{{' }} name {{ '}}'  }} mode=775 state=directory owner=www-data group=www-data recurse=yes
  notify:
    - Reload Nginx

- name: Creates dir for ssl cert
  file: path=/etc/nginx/ssl state=directory owner=www-data group=www-data mode=0775

- name: Copy temp.php
	copy: src=files/temp.php dest=/var/www/{{ '{{' }} name {{ '}}'  }}/ mode=0644


- name: Creates dir for worker
  file: path=/opt/worker state=directory owner=www-data group=www-data mode=0775

- name: Copy worker.php
      copy: src=files/worker.php dest=/opt/worker/ mode=0644

- name: clone git repo for pecl-gearman (php 7.0 supported) and install/config it
	git: repo=https://github.com/wcgallego/pecl-gearman.git dest=/tmp/peclgearman
	file: path=/tmp/peclgearman state=directory owner=root group=root mode=0775
	command: phpize chdir=/tmp/peclgearman
	command: ./configure chdir=/tmp/peclgearman
	command: make install chdir=/tmp/peclgearman
	command: "extension=gearman.so" > /etc/php/7.0/mods-available/gearman.ini
	command: phpenmod -v ALL -s ALL gearman

- name: installs needed packages for gearman
  apt: name={{ item }} state=latest
  with_items:
	- gearman-job-server 
	- php-pear libgearman-dev
	-php7.0-dev  
	-supervisor
	-php7.0-fpm
	-php-curl
	-unzip
	-re2c
	-libgearman-dev
  notify:
	- Start gearman server
	- Start php-fpm

- name: create symlink for phpfpm
	file:
	    src: /etc/php/7.0/mods-available/gearman.ini
	    dest: /etc/php/7.0/fpm/20-gearman.ini
	    state: link

- name: create self-signed SSL cert
  command: openssl req -new -nodes -x509 -subj "/C=AR/ST=Oregon/L=Portland/O=IT/CN=api.tempstats.com" -days 3650 -keyout /etc/nginx/ssl/server.key -out /etc/nginx/ssl/server.crt -extensions v3_ca creates=/etc/nginx/ssl/server.crt
  notify: reload nginx


- name: Copy supervisor file for worker
      copy: src=files/worker.conf dest=/etc/supervisor/conf.d/ mode=0644

- name: make worker monitored by supervisord
  supervisorctl: name=worker state=started

