---
- name: Start Nginx
  service: name=nginx state=started

- name: Reload Nginx
  service: name=nginx state=reloaded

- name: Restart Nginx
  service: name=nginx state=restarted

- name: Start gearman server
  service: name=gearman-job-server state=started

- name: Start php-fpm
  service: name=php7.0-fpm state=started

- name: Restart php-fpm
  service: name=php7.0-fpm state=restarted

- name: Restart supervisor
  service: name=supervisor state=restarted
